### ISSUE TITLE
希望增加一个旋转当前画面的功能，epub格式的漫画有些长图直接做成竖页的，电脑上只能歪着脖子看

### ISSUE THREAD

**Issue by GreenIsMyFavourite** [RuliaReader/Rulia#101]
希望增加一个旋转当前画面的功能

**Comment by LancerComet** [comment]
可以搞

**Comment by LancerComet** [comment]
图片旋转：

![image](https://github.com/RuliaReader/Rulia/assets/10321350/3e99a062-f52d-42c0-be98-d8e4be5193ad)

图片旋转功能设计为控制单张图片旋转，这样做更合理.

旋转后可以放大，是整个界面一起放大，图片单独放大是有点怪的

![image](https://github.com/RuliaReader/Rulia/assets/10321350/50e3cfbc-d8c0-4df9-86ee-0b0992c39ef8)

![image](https://github.com/RuliaReader/Rulia/assets/10321350/55ae0c0e-2ba2-4a84-bbd3-d57713b57d5a)

无限模式由于是连续图片展示，不支持旋转.

**Comment by LancerComet** [comment]
Done
