### ISSUE TITLE
无法付款

### ISSUE THREAD

**Issue by foolmos** [RuliaReader/Rulia#119]
登录帐号提示错误
![PixPin_2024-03-05_13-05-14](https://github.com/RuliaReader/Rulia/assets/78858135/1648cbf2-9e3a-456c-930d-a363a279cd03)

**Comment by foolmos** [comment]
原来是梯子问题，关了就付好了

**Comment by LancerComet** [comment]
UWP 程序在 Windows 系统开启本地代理服务器（127.0.0.1）时会无法访问网络，如果需要的话可以使用 https://github.com/tiagonmas/Windows-Loopback-Exemption-Manager 来解决这个问题

感谢支持！如果还有其他问题请随时 reopen the issue

![image](https://github.com/RuliaReader/Rulia/assets/10321350/8e904b15-64f3-4628-805e-533622fab8c9)
