### ISSUE TITLE
文件按名称排序方式存在缺陷

### ISSUE THREAD

**Issue by Tiline28** [RuliaReader/Rulia#121]
在带有多位数编号的文件中，容易出现排序紊乱的问题，请问能否将获取到的连续数字组合成一个整型再进行排序？
![{984E1DD6-4F23-438a-9AD7-71840097018D}](https://github.com/RuliaReader/Rulia/assets/88189454/35d3632e-b304-4252-9fc0-e84678e82009)

**Comment by LancerComet** [comment]
![image](https://github.com/RuliaReader/Rulia/assets/10321350/b5baa761-0283-4068-abbc-250e459277a5)

没遇到，我感觉你的系统怪怪的

![image](https://github.com/RuliaReader/Rulia/assets/10321350/58bd43d3-3864-403c-a943-f8ff62050da5)

**Comment by LancerComet** [comment]
Closed: Unable to reproduce.
