### ISSUE TITLE
10 bit AVIF decoding issue | 怎么装完扩展还是打不开 AVIF 格式文件

### ISSUE THREAD

**Issue by WuM9418** [RuliaReader/Rulia#129]
0xC00D36B4

**Comment by LancerComet** [comment]
图挂了，能重新上传一下么，另外最好可以上传一下 AVIF 样本

**Comment by WuM9418** [comment]
> 图挂了，能重新上传一下么，另外最好可以上传一下 AVIF 样本

0xC00D36B4

**Comment by WuM9418** [comment]
[Uploading 地狱开曼.zip…]()

**Comment by WuM9418** [comment]
[地狱开曼.zip](https://github.com/RuliaReader/Rulia/files/14812937/default.zip)

**Comment by LancerComet** [comment]
看了一下，如果用 Windows Photo 打开，提示需要安装 https://apps.microsoft.com/detail/9mvzqvxjbq9v，但是安装完毕依然无法打开，那么看来微软的解码器无法正确解码这一组 AVIF，我对 AVIF 了解不多，但我猜测 AVIF 可能和 WEBP 一样有多种编码方式，微软的方案没有全部支持；目前 Rulia 使用的是微软提供的解码器，因为 UWP 环境很难使用别的 AV1 解码器，暂时我的建议是转换为 JPEG 或者 PNG，这个问题短期内很难处理.

**Comment by LancerComet** [comment]
![image](https://github.com/RuliaReader/Rulia/assets/10321350/15740137-d804-4cde-8eac-949de9d2d8e5)

不过我比较了一下，我弄了另外三张 AVIF，都可以在 Windows 中正常打开，分别是漫画 01.avif 的 AVIF 重新保存，B 站的 AVIF 图片，AVIF Checker 的示例图片，在不了解 HEIF 容器和 AV1 之前，我暂时也怀疑漫画图片中的 AVIF 包含了某种奇怪的编码方式.

**Comment by WuM9418** [comment]
> ![图像](https://private-user-images.githubusercontent.com/10321350/319083127-15740137-d804-4cde-8eac-949de9d2d8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDcyMzQsIm5iZiI6MTcxMjE0NjkzNCwicGF0aCI6Ii8xMDMyMTM1MC8zMTkwODMxMjctMTU3NDAxMzctZDgwNC00Y2RlLThlYWMtOTQ5ZGU5ZDJkOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEyMjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYzdiNjBiMjZlMWFmNzRlZmQ2YjM4YTJiNzFmOGIwODA0Zjc4MzE1NmFjZmZiMmFjNjQ1ZDExODIzYjNjNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aX0V-yWxasN7LoHIgDnhdFXCT1Ezh9kJuoA9l5fDSrg)
> 
> 不过我比较了一下，我弄了另外三张 AVIF，都可以在 Windows 中正常打开，分别是漫画 01.avif 的 AVIF 重新保存，B 站的 AVIF 图片，AVIF Checker 的示例图片，在不了解 HEIF 容器和 AV1 之前，我暂时也怀疑漫画图片中的 AVIF 包含了某种奇怪的编码方式.

好的，我给丢到komga了，只是违背了在本地看漫画的初衷。。。

**Comment by LancerComet** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/10321350/319083127-15740137-d804-4cde-8eac-949de9d2d8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDcyMzQsIm5iZiI6MTcxMjE0NjkzNCwicGF0aCI6Ii8xMDMyMTM1MC8zMTkwODMxMjctMTU3NDAxMzctZDgwNC00Y2RlLThlYWMtOTQ5ZGU5ZDJkOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEyMjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYzdiNjBiMjZlMWFmNzRlZmQ2YjM4YTJiNzFmOGIwODA0Zjc4MzE1NmFjZmZiMmFjNjQ1ZDExODIzYjNjNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aX0V-yWxasN7LoHIgDnhdFXCT1Ezh9kJuoA9l5fDSrg)
> > 不过我比较了一下，我弄了另外三张 AVIF，都可以在 Windows 中正常打开，分别是漫画 01.avif 的 AVIF 重新保存，B 站的 AVIF 图片，AVIF Checker 的示例图片，在不了解 HEIF 容器和 AV1 之前，我暂时也怀疑漫画图片中的 AVIF 包含了某种奇怪的编码方式.
> 
> 好的，我给丢到komga了，只是违背了在本地看漫画的初衷。。。

我现在在研究新的解码方案，希望能有好消息

**Comment by LancerComet** [comment]
现在已经可以正常打开了：

![image](https://github.com/RuliaReader/Rulia/assets/10321350/81f79add-074e-4597-bd7d-315cf1437817)

**Comment by LancerComet** [comment]
Related issue: https://answers.microsoft.com/zh-hans/insider/forum/all/windows-11/e868c730-387f-4e23-a359-754225ac2668

**Comment by LancerComet** [comment]
已经处理完毕，新版本发布.

**Comment by WuM9418** [comment]
> 已经处理完毕，新版本发布.

🐂🐸
