### ISSUE TITLE
[Bug Report]无法读取嵌套文件（夹）

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/Rulia#130]
![image](https://github.com/RuliaReader/Rulia/assets/67213568/5aad4281-f7cb-4d6f-a533-38fc5d468187)
如图可见，我的文件层次是这样的：
```
别当欧尼酱了！官方同人集
　别当欧尼酱了！官方同人集（来自动漫之家）
　　 别当欧尼酱了！官方同人集（来自动漫之家）.cbz
　　 别当欧尼酱了！官方同人集,别当欧尼酱了！官方同人集在线漫画-动漫之家漫画网 - 动漫之家漫画网 (2024_3_29 11_12_12).html
　第二册
　　 （其中文件省略）
```
- 当我直接添加「别当欧尼酱了！官方同人集」这个文件夹的时候，显示里面有零本漫画，无法在软件里看到里面的漫画
- 当我添加「别当欧尼酱了！官方同人集（来自动漫之家）」这个子文件夹时，可以读取到里面的漫画
见下：
![image](https://github.com/RuliaReader/Rulia/assets/67213568/5ad21354-b70a-4a2b-9031-aa2cc4970aed)

希望能增加多层文件夹的支持（比如[Cover](https://www.microsoft.com/store/productId/9WZDNCRFJ9W7)支持）

**Comment by LancerComet** [comment]
子文件夹嵌套在这里开启（需要 Premium）：

![image](https://github.com/RuliaReader/Rulia/assets/10321350/405326c1-00dc-49fb-90b7-146d5273e3ff)
