### ISSUE TITLE
[Bug Report]亮度滑条与预期不一致

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/Rulia#131]
![image](https://github.com/RuliaReader/Rulia/assets/67213568/9937829e-20bf-4f37-9887-64d18e00beca)
![image](https://github.com/RuliaReader/Rulia/assets/67213568/1e5164d8-62ad-46b0-90bf-16d32a04a686)
如图，亮度条拉到最小时最亮，拉到最大时最暗，与一般的理解相反

**Comment by LancerComet** [comment]
这个是从哔哩哔哩漫画 UWP 沿用过来的老设计，给老用户交互做兼容的，现在 Rulia 已经一年了，用户的交互习惯基本养成，如果没有大问题不会再改了.
