### ISSUE TITLE
[Feature Request] Ability to hide buttons in AppTitleBar in FullScreen mode | 真正的沉浸式全屏

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/Rulia#132]
![FullScreen](https://github.com/RuliaReader/Rulia/assets/67213568/0528dfdf-88fd-4a9a-9daf-3e159e913812)
如图所示，全屏状态下还是有三处其他元素，希望能完全隐藏这些按钮，让屏幕只剩下漫画。这些菜单可通过<kbd>ESC</kbd>或者右键调出

**Comment by LancerComet** [comment]
右上角目前无法关闭，右下角现在就可以关闭：

![image](https://github.com/RuliaReader/Rulia/assets/10321350/1cdbd570-65eb-4d08-becc-f4cbaa9c6a6f)

**Comment by Jiang10086** [comment]
> 右上角目前无法关闭，右下角现在就可以关闭：
> 
> ![image](https://private-user-images.githubusercontent.com/10321350/319066728-1cdbd570-65eb-4d08-becc-f4cbaa9c6a6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDE3MzMsIm5iZiI6MTcxMjU0MTQzMywicGF0aCI6Ii8xMDMyMTM1MC8zMTkwNjY3MjgtMWNkYmQ1NzAtNjVlYi00ZDA4LWJlY2MtZjRjYmFhOWM2YTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAxNTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNTkzNjNhMmZkMWMxNzJhNDhmMmFlM2JkZDQ2N2M5YWM3NWM1MjQyMjM5N2Q3YmExZmMwMmQ1NjQ1YzZhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.36Tostc2I0kVTo2c-zQLaLW2nB_bFfqMQG-jMQqN2dU)

不好意思没有仔细看，原来还有关闭的选项

**Comment by LancerComet** [comment]
Done
