### ISSUE TITLE
[Bug Report] Windows截图快捷键会使全屏的Rulia最小化

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/Rulia#134]
https://github.com/RuliaReader/Rulia/assets/67213568/60719082-3f13-4415-aa44-8d1e4718a816

如视频所示，在我在Windows 11下全屏Rulia并按下使用<kbd>Win</kdb>+<kbd>Shift</kdb>+<kbd>S</kbd>截屏后，Rulia会自动最小化到任务栏

**Comment by LancerComet** [comment]
我试了一下所有 UWP 都这样，系统行为
