### ISSUE TITLE
Cover streams are closed unexpectedly | 请问0.18.1版本是否在读取文件夹自定义封面处做了修改？

### ISSUE THREAD

**Issue by Tiline28** [RuliaReader/Rulia#141]
在更新后，部分文件夹的封面无法正常显示，在使用我所存有的图片多次尝试后，发现：
不可正常显示的封面中，最大的分辨率为540 540；
在可以正常显示的封面中，最小的分辨率为558 568.

**Comment by Tiline28** [comment]
不可正常显示的封面中，最大的分辨率为540*540；
在可以正常显示的封面中，最小的分辨率为558*568.

**Comment by Tiline28** [comment]
不可正常显示的封面中，最大的分辨率为540/*540；
在可以正常显示的封面中，最小的分辨率为558/*568.

**Comment by LancerComet** [comment]
封面的文件流提前关闭了

**Comment by LancerComet** [comment]
Done
