### ISSUE TITLE
自定义封面似乎仍存在缺陷

### ISSUE THREAD

**Issue by Kirinni** [RuliaReader/Rulia#144]
在0.18.2版本中，大部分封面都恢复了显示，但有些封面无法显示，这些有问题的封面在0.18.2版本之前是可用的。
该问题似乎不是由分辨率引发的，我使用了与这些封面分辨率近似的图片，它们都能正常显示。
我不清楚这些图片与其他图片有何种差别。

此外，10bit色深的avif图片也无法作为封面显示，但我想这可能不会造成太大影响。

以下是有问题的图片的压缩包：
[cover.zip](https://github.com/RuliaReader/Rulia/files/15145254/cover.zip)

**Comment by LancerComet** [comment]
Shipped with 0.18.3.
