### ISSUE TITLE
双页布局下的宽图自动检测

### ISSUE THREAD

**Issue by dyphire** [RuliaReader/Rulia#155]
目前的双页布局强制必须显示两页，当其中一页是宽图（甚至两页都有可能是宽图）的情况下显示效果极差
![image](https://github.com/RuliaReader/Rulia/assets/61936050/16c24f22-d7d1-4fee-af17-0d34ac50d8b3)
![image](https://github.com/RuliaReader/Rulia/assets/61936050/a8b3d58f-f410-4e9b-96c0-612f66c83af8)

双页布局需要添加宽图检测，当检测到是宽图时应单独显示宽图而不是和其他页拼接

**Comment by dyphire** [comment]
演示下支持此功能的阅读器的效果

https://github.com/RuliaReader/Rulia/assets/61936050/77fa13f7-74fc-4070-b9f6-feb68f13a589

**Comment by dyphire** [comment]
才发现还有个自动模式实现了宽图自动检测和单独显示
![image](https://github.com/RuliaReader/Rulia/assets/61936050/9cefef4f-e1b8-4187-812c-d1be028e856f)
但自动模式不支持第一页空白的显示，导致很多漫画的双页拼接都是错误的。自动模式应该合并到双页模式中，没有理由拆分它们保留一个显示会出现问题的模式

**Comment by LancerComet** [comment]
暂时不做修改

**Comment by dyphire** [comment]
不做修改怎么正确显示？至少也为自动布局添加第一页空白的功能，否则没有一个能正确显示双页拼接的布局，作为漫画阅读器也太失格了
