### ISSUE TITLE
[Feature Request] Support cb7 format | 支持cb7格式

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/Rulia#171]
This software supports 7z but not cb7. However, 7z is generally recognized as a compressed package and is not very suitable as a comic format. I like to rename it to cb7. I hope Rulia can support this format.

这个软件支持7z但是不支持cb7，但是7z一般会被识别为压缩包，不太适合作为漫画的格式。我喜欢重命名为cb7，希望Rulia能支持这个格式

**Comment by LancerComet** [comment]
Will be shipped with 0.21.0
