### ISSUE TITLE
Aliasing issues, especially when blank area trimming is turned on

### ISSUE THREAD

**Issue by eao** [RuliaReader/Rulia#94]
Hi, I love the design of your app.  And it was the only image viewer/manga reader for Windows I could find which had border cropping/blank area trimming functionality.  However, I noticed some aliasing issues which affect the image quality.

My current setup for reading manga is the app Honeyview on a 1080x1920 screen (portrait mode).  I use the "Soften" filter and "Lanczos" interpolation options.  This is how a 2-page spread with a size of 3000x2250 looks when shrunk down to fit the size of my screen, in Honeyview:

![honeyview](https://github.com/RuliaReader/Rulia/assets/34289076/f5af9963-40c6-40e1-91a7-40df25586ed6)

And this is how the same image looks in Rulia, without any blank area trimming.  There is more aliasing than in Honeyview.

![rulia without trimming](https://github.com/RuliaReader/Rulia/assets/34289076/e23862dd-9912-4500-94aa-435a6b555eb1)

And third, this is how the same image looks in Rulia when blank area trimming is turned on.  There is even more aliasing than before.

![rulia with blank area trimming](https://github.com/RuliaReader/Rulia/assets/34289076/fae5c304-196b-4064-99d6-a18be2b5f4a6)

And finally, here is a zoomed-in comparison of one of the more detailed sections of the image:

![rulia comparison](https://github.com/RuliaReader/Rulia/assets/34289076/bf483d02-133e-487b-b1d0-4c7d4c5cdcb6)

I wonder if anything can be done to fix this aliasing, because I want very much to use your app for the blank area trimming feature.  Thank you very much for your time.

**Comment by LancerComet** [comment]
Thank you for your feedback. 

I haven't compared the differences in image scaling in such detail with other reader yet. Different reader may use madifferent scaling algorithms, which can result in some variations. Since I haven't implemented a separate option to control how scaling is handled, there isn't currently a specific solution.

However you can try enabling the "Noise Reduction" feature, as it applies some processing to the image, I guess it may alleviate this issue.

**Comment by LancerComet** [comment]
BTW, I have updated the border cropping algorithm for next version. It is more aggressive but still being accurate. The left is the current version, the right is the next version.

![image](https://github.com/RuliaReader/Rulia/assets/10321350/bb6f2a4b-daeb-4ce8-92d7-7cfdef60f348)

**Comment by LancerComet** [comment]
I am closing this issue, feel free to reopen it if you have anything to ask
